apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "need to set some name for deployment" .Values.name }}
  annotations:
    chart: {{ default .Chart.Name .Values.nameOverride }}
  labels:
    app: nginx
