apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  annotations:
    chart: {{ default .Chart.Name .Values.nameOverride }}
  labels:
    app: {{ .Values.app.name }}
    addon: {{ .Values.app.name }}
    triple: {{ .Values.app.name }}
